name: release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-18.04
    container: nvidia/cuda:10.2-devel-ubuntu18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
         submodules: recursive
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Announce version
        run: echo "creating library for ${GIT_TAG_NAME}"
      - name: Install deps
        run: |
          apt-get update -y
          apt-get update
          apt-get install cmake openjdk-11-jdk default-jdk -y
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      - name: Build project
        run: |
          cmake -H. -Bbuild
          make -C build yacx
          make -C build yacx-jni
          export unix_dir=yacx-v${GIT_TAG_NAME}_unix/
          mkdir -p dist/$unix_dir/java/bin/
          cp build/libyacx.so dist/$unix_dir
          cp build/libyacx-jni.so dist/$unix_dir
          cp -R build/java/bin/yacx/ dist/$unix_dir/java/bin/
      - name: Upload release artifacts
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: xz
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
